### ISSUE TITLE
Two new features for educational uses

### ISSUE THREAD

**Issue by barichello** [nileshbohra/nerdle-game#4]
Would it be possible to create a version with more columns (12, for instance) and include the possibility of using parenthesis?

It would be great to use it to practice numerical expressions on math lessons

**Comment by nileshbohra** [comment]
Yes, it's possible, please give me 5 equations with parenthesis or other things you might want to add for reference.

**Comment by barichello** [comment]
3 expressions with 12 digits:

2+34*2-50=20
60/3+113=133
50-60+100=90

2 expressions with 12 digits and parenthesis:

2*(17+21)=76
59-3*(12)=23

**Comment by nileshbohra** [comment]
Hi, i've added the feature you requested, please select the mode as maxi to play, please send feedback if anything goes wrong, cheers 🎉.
